name: Merge M3U Playlists

on:
  push:
    paths:
      - 'SHOOF'
      - 'rotana'
      - 'ART'
      - 'shahid'
      - 'STCtv'
      - 'StarzPlay'
      - 'SHASHA'
      - 'ARABIC'
      - 'GLOBAL'
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Merge playlists
        run: |
          echo "#EXTM3U" > all.m3u
          for file in SHOOF rotana ART shahid STCtv StarzPlay SHASHA  ARABIC GLOBAL; do
            if [ -f "$file" ]; then
              echo "" >> all.m3u
              grep -v "^#EXTM3U" "$file" >> all.m3u || true
            fi
          done

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add all.m3u
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-merge playlists"
          git push
